apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.enviroment.name }}-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  type:  {{ .Values.service.type }}
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.container.port }}